### ISSUE TITLE
Adding new question with start and end date error

### ISSUE THREAD

**Issue by iCarrrot** [czapiga/IZP-glosowanie#3]
There is an error while question with filled both end and start date is saving.

**Comment by czapiga** [comment]
Please fix it under #5

**Comment by iCarrrot** [comment]
Well, I don't know how to. I was just testing it, and I just wanted to leave this for somebody who is working with this part of code. 
More info what cause this issue:
- In admin panel choose new question
- Set whatever start date

-

**Comment by czapiga** [comment]
Never mind, I'll fix that.
