### ISSUE TITLE
Strona główna

### ISSUE THREAD

**Issue by sgorawski** [czapiga/IZP-glosowanie#30]
Obecnie po kliknięciu w link "POKAŻ STRONĘ" na panelu administracyjnym zwracamy 404, jako że nie obsługujemy linka "/" w izp.urls. Sugeruję albo zmienić zachowanie panelu administracyjnego (co nie wiem jak zrobić), albo ustawić proste przekierowanie z "/" na "/polls".

**Comment by czapiga** [comment]
I'm waiting for PR :)

**Comment by sgorawski** [comment]
Opened ~20 mins ago afaict :)

**Comment by sgorawski** [comment]
Will do :)

**Comment by czapiga** [comment]
What is status of this task?

**Comment by sgorawski** [comment]
I tried like 3 different solutions for the issue, but could not get any to actually work, so for now I'm stuck tbh. I will be looking at it again when I have time, unless this is urgent - in that case do as you see fit.

**Comment by czapiga** [comment]
Let it be your main task for this week.

**Comment by sgorawski** [comment]
I finally managed to get it to work - the resulting code is really simple in the end, once I got it right. Perhaps it is not the most elegant solution, but it works as expected. It does not look like big task, so if you approve the PR I think I'll start working on my other issue (as my task for the week).
